### ISSUE TITLE
HttpModule doesn't register on IIS 7+

### ISSUE THREAD

**Issue by MaurizioPz** [rencore/SharePoint-Software-Factory#1]
SharePoint-Software-Factory/SPALM.SPSF/Templates/Text/HttpModule/FeatureReceiverCode.xml.t4
contains this line  SPWebConfigModification mod = new SPWebConfigModification("add[@type='<#= ProjectNamespace #>.<#= HttpModuleClass #>, <#= ProjectAssemblyName #>']", "configuration/system.web/httpModules");
this works fine for IIS 6, but for IIS 7+ it should be
 SPWebConfigModification mod = new SPWebConfigModification("add[@type='<#= ProjectNamespace #>.<#= HttpModuleClass #>, <#= ProjectAssemblyName #>']", "configuration/system.webServer/modules");

**Comment by matthiaseinig** [comment]
Thanks for reporting in.
