### ISSUE TITLE
SPField of type URL with format Image, generated with wrong schema

### ISSUE THREAD

**Issue by MaurizioPz** [rencore/SharePoint-Software-Factory#2]
The file SharePoint-Software-Factory/SPALM.SPSF.Library/CustomWizardPages/SiteColumnWizard.Designer.cs
contains this line:

```
 this.comboBoxHyperlinkOrPicture.Items.AddRange(new object[] {
 "Hyperlink",
 "Picture"});
```

it should be

```
 this.comboBoxHyperlinkOrPicture.Items.AddRange(new object[] {
 "Hyperlink",
 "Image"});
```

http://msdn.microsoft.com/en-us/library/office/aa979575%28v=office.15%29.aspx (look under Format)

**Comment by matthiaseinig** [comment]
Thanks Maurizio. Please feel free to submit pull request, which will make the fixes much quicker :)
